databases:
  - name: collaborative-forms-db
    plan: free
    databaseName: collaborative_forms
    user: collaborative_forms

services:
  - type: redis
    name: collaborative-forms-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all
        
  - type: web
    name: collaborative-forms
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'cd collaborative_forms && python -m gunicorn collaborative_forms.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ebullioscopic-forms
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: collaborative-forms-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
